# name: Update playlist with Spotify Auth
# on:
#   push:
#     branches:
#       - main
# jobs:
#   spotify-auth-and-apply:
#     runs-on: ubuntu-latest
#     name: Apply
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Setup Go
#         uses: actions/setup-go@v5
#         with:
#           go-version: '1.18.0'

#       - name: Install spotify_auth_proxy
#         run: go install github.com/conradludgate/terraform-provider-spotify/spotify_auth_proxy@latest

#       - name: Run spotify_auth_proxy and capture Auth URL
#         env:
#           SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
#           SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
#           SPOTIFY_CLIENT_REDIRECT_URI: ${{ secrets.SPOTIFY_CLIENT_REDIRECT_URI }}
#         run: |
#           spotify_auth_proxy > proxy_output.log 2>&1 &
#           PROXY_PID=$!
#           echo "PROXY_PID=$PROXY_PID" >> $GITHUB_ENV

#           # Wait for the Auth URL and API Key to appear in the log
#           while ! (grep -q "Auth URL:" proxy_output.log && grep -q "APIKey:" proxy_output.log); do
#             sleep 1
#           done

#           auth_url=$(grep "Auth URL:" proxy_output.log | awk '{print $3}')
#           api_key=$(grep "APIKey:" proxy_output.log | awk '{print $2}')
#           echo "AUTH_URL=$auth_url" >> $GITHUB_ENV
#           echo "SPOTIFY_API_KEY=$api_key" >> $GITHUB_ENV


#       - name: Setup Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: '18'

#       - name: Install Puppeteer
#         run: npm install puppeteer

#       - name: Perform Spotify login
#         env:
#           SPOTIFY_USERNAME: ${{ secrets.SPOTIFY_USERNAME }}
#           SPOTIFY_PASSWORD: ${{ secrets.SPOTIFY_PASSWORD }}
#         run: |
#           node - <<EOF
#           const puppeteer = require('puppeteer');

#           (async () => {
#             const browser = await puppeteer.launch({ headless: true });
#             const page = await browser.newPage();

#             try {
#               await page.goto('${{ env.AUTH_URL }}');

#               // Wait for login form and fill in credentials
#               await page.waitForSelector('#login-username');
#               await page.type('#login-username', process.env.SPOTIFY_USERNAME);
#               await page.type('#login-password', process.env.SPOTIFY_PASSWORD);

#               // Submit the form
#               await page.click('#login-button');

#               // Wait for redirect and authorization
#               await page.waitForNavigation({ waitUntil: 'networkidle0' });

#               // Check for successful authorization
#               const content = await page.content();
#               if (content.includes('Authorization successful')) {
#                 console.log('Spotify authorization successful');
#               } else {
#                 throw new Error('Authorization not successful');
#               }
#             } catch (error) {
#               console.error('Error during Spotify login:', error);
#               process.exit(1);
#             } finally {
#               await browser.close();
#             }
#           })();
#           EOF
#       - name: Run Terraform Apply
#         run: |
#           terraform init
#           terraform apply -var="SPOTIFY_API_KEY=${{ env.SPOTIFY_API_KEY }}" -auto-approve
name: Update playlist with Spotify Auth

on:
  push:
    branches:
      - main

jobs:
  spotify-auth-and-apply:
    runs-on: ubuntu-latest
    name: Apply
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.18.0'

      - name: Install spotify_auth_proxy
        run: go install github.com/conradludgate/terraform-provider-spotify/spotify_auth_proxy@latest

      - name: Run spotify_auth_proxy and capture Auth URL
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_CLIENT_REDIRECT_URI: ${{ secrets.SPOTIFY_CLIENT_REDIRECT_URI }}
        run: |
          spotify_auth_proxy > proxy_output.log 2>&1 &
          PROXY_PID=$!
          echo "Waiting for Auth URL and API Key..."
          for i in {1..30}; do
            if grep -q "Auth URL:" proxy_output.log && grep -q "APIKey:" proxy_output.log; then break; fi
            sleep 1
          done
          if ! (grep -q "Auth URL:" proxy_output.log && grep -q "APIKey:" proxy_output.log); then
            echo "❌ Failed to get Auth URL or API Key"; cat proxy_output.log; exit 1
          fi
          auth_url=$(grep "Auth URL:" proxy_output.log | awk '{print $3}')
          api_key=$(grep "APIKey:" proxy_output.log | awk '{print $2}')
          echo "AUTH_URL=$auth_url" >> $GITHUB_ENV
          echo "SPOTIFY_API_KEY=$api_key" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Puppeteer and dependencies
        run: |
          npm install puppeteer
          npm install fs-extra

      - name: Perform Spotify login and authorization
        env:
          SPOTIFY_USERNAME: ${{ secrets.SPOTIFY_USERNAME }}
          SPOTIFY_PASSWORD: ${{ secrets.SPOTIFY_PASSWORD }}
        run: |
          node - <<'EOF'
          const puppeteer = require('puppeteer');
          const fs = require('fs-extra');

          // Utility functions
          const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
          const randomDelay = (min, max) => Math.floor(Math.random() * (max - min + 1) + min);
          
          async function typeWithHumanDelay(page, selector, text) {
            for (const char of text) {
              await page.type(selector, char, { delay: randomDelay(30, 120) });
              if (Math.random() > 0.7) await delay(randomDelay(50, 200));
            }
          }

          async function clickByText(page, text, elementType = 'button') {
            const elements = await page.$$(elementType);
            for (const element of elements) {
              const elementText = await page.evaluate(el => el.textContent?.trim(), element);
              if (elementText?.toLowerCase().includes(text.toLowerCase())) {
                await element.click();
                return true;
              }
            }
            return false;
          }

          async function safeClick(page, selector, timeout = 10000) {
            await page.waitForSelector(selector, { visible: true, timeout });
            await delay(500);
            const element = await page.$(selector);
            if (element) {
              await element.click();
              return true;
            }
            return false;
          }

          (async () => {
            const browser = await puppeteer.launch({
              headless: true,
              args: ['--no-sandbox', '--disable-setuid-sandbox'],
              defaultViewport: { width: 1280, height: 800 }
            });

            const page = await browser.newPage();
            await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36');

            try {
              // Step 1: Open Auth URL
              console.log("🌐 Navigating to Spotify Auth URL...");
              await page.goto(process.env.AUTH_URL, { waitUntil: 'networkidle2', timeout: 60000 });
              await delay(3000);

              // Handle cookies if present
              try {
                const cookieAccepted = await clickByText(page, 'accept', 'button') || 
                                      await safeClick(page, '#onetrust-accept-btn-handler');
                if (cookieAccepted) {
                  console.log("🍪 Accepted cookies");
                  await delay(2000);
                }
              } catch (e) {
                console.log("ℹ️ No cookie banner found");
              }

              // Step 2: Enter email and continue
              console.log("📧 Entering email...");
              await page.waitForSelector('input[type="email"], #login-username', { visible: true, timeout: 15000 });
              await typeWithHumanDelay(page, 'input[type="email"], #login-username', process.env.SPOTIFY_USERNAME);
              await delay(1000);

              console.log("➡️ Clicking Continue...");
              const continueClicked = await clickByText(page, 'continue') || 
                                     await safeClick(page, 'button[data-testid="login-button"]');
              if (!continueClicked) throw new Error("Continue button not found");
              await delay(4000);

              // Step 3: Handle OTP/password choice
              console.log("🔍 Checking for OTP/password choice...");
              try {
                // Check if we're on OTP screen by looking for "6-digit code" text
                const otpText = await page.evaluate(() => {
                  return Array.from(document.querySelectorAll('*'))
                    .find(el => el.textContent?.includes('6-digit code'));
                });

                if (otpText) {
                  console.log("🔢 Found OTP screen, switching to password login...");
                  const passwordOptionClicked = await clickByText(page, 'log in with a password') || 
                                              await safeClick(page, 'button[data-encore-id="buttonTertiary"]');
                  if (!passwordOptionClicked) {
                    throw new Error("Password login option not found on OTP screen");
                  }
                  await delay(3000);
                }
              } catch (e) {
                console.log("ℹ️ OTP screen not detected, proceeding with password entry");
              }

              // Step 4: Enter password
              console.log("🔑 Entering password...");
              await page.waitForSelector('input[type="password"], #login-password', { visible: true, timeout: 10000 });
              await typeWithHumanDelay(page, 'input[type="password"], #login-password', process.env.SPOTIFY_PASSWORD);
              await delay(1500);

              console.log("🚀 Submitting login...");
              const loginClicked = await clickByText(page, 'log in') || 
                                  await safeClick(page, '#login-button');
              if (!loginClicked) throw new Error("Login button not found");
              await delay(5000);

              // Handle potential "Stay logged in" prompt
              try {
                const stayLoggedIn = await clickByText(page, 'stay logged in') || 
                                     await safeClick(page, '[data-testid="auth-accept"]');
                if (stayLoggedIn) {
                  console.log("🔘 Clicked 'Stay Logged In'");
                  await delay(2000);
                }
              } catch (e) {
                console.log("ℹ️ No 'Stay Logged In' prompt found");
              }

              // Step 5: Handle authorization
              console.log("🔄 Checking for authorization screen...");
              try {
                const authAccepted = await clickByText(page, 'agree') || 
                                     await safeClick(page, '#auth-accept');
                if (authAccepted) {
                  console.log("✅ Clicked 'Agree' on authorization screen");
                  await page.waitForNavigation({ waitUntil: 'networkidle0', timeout: 15000 });
                }
              } catch (e) {
                console.log("ℹ️ No authorization screen detected");
              }

              // Verification
              const currentURL = page.url();
              if (currentURL.includes('callback?code=')) {
                console.log('🎉 Spotify authorization successful!');
              } else {
                throw new Error(`Authorization failed. Current URL: ${currentURL}`);
              }

            } catch (error) {
              console.error('💥 Error during Spotify login:', error.message);
              await page.screenshot({ path: 'spotify_error.png', fullPage: true });
              await fs.writeFile('error_debug.html', await page.content());
              throw error;
            } finally {
              await browser.close();
            }
          })();
          EOF

      - name: Run Terraform Apply
        run: |
          terraform init
          terraform apply -var="SPOTIFY_API_KEY=${{ env.SPOTIFY_API_KEY }}" -auto-approve

      - name: Upload debug files (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: spotify-debug
          path: |
            spotify_error.png
            error_debug.html